-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_category"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "parent_id"   bigint   NOT NULL,
    "name"        varchar  NOT NULL,
    "sort"        int,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '成本分类';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_unit"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar  NOT NULL,
    "type"        varchar  NOT NULL,
    "remark"      varchar,
    "sort"        int,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '成本计量单位';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_property"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar  NOT NULL,
    "remark"      varchar,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '成本属性项';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_property_value"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "property_id" bigint   NOT NULL,
    "name"        varchar  NOT NULL,
    "remark"      varchar,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '成本属性值';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_category_property"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "category_id" bigint   NOT NULL,
    "property_id" bigint   NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '分类属性关系';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_brand"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar  NOT NULL,
    "description" varchar,
    "img_url"     varchar,
    "sort"        int,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '成本品牌';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_category_brand"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "category_id" bigint   NOT NULL,
    "brand_id"    bigint   NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '分类品牌关系';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_material_spu"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar  NOT NULL,
    "unit_id"     bigint   NOT NULL,
    "category_id" bigint   NOT NULL,
    "description" varchar,
    "img_url"     varchar,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '材料spu';

-- 将该建表 SQL 语句，添加到 bpcm-module-cost-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cost_material_sku"
(
    "id"          bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "spu_id"      bigint   NOT NULL,
    "properties"  varchar  NOT NULL,
    "brand_id"    bigint,
    "description" varchar,
    "img_url"     varchar,
    "status"      int      NOT NULL,
    "creator"     varchar           DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar           DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '材料sku';