-- 将该建表 SQL 语句，添加到 bpcm-module-material-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "material_rfq"
(
    "id"            bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code"          varchar  NOT NULL,
    "category_id"   bigint   NOT NULL,
    "delivery_date" varchar  NOT NULL,
    "sub_type" int NOT NULL,
    "status"        int      NOT NULL,
    "notes"         varchar,
    "creator"       varchar           DEFAULT '',
    "create_time"   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar           DEFAULT '',
    "update_time"   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"       bit      NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '材料询价清单';

-- 将该建表 SQL 语句，添加到 bpcm-module-material-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "material_rfq_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rfq_id" bigint NOT NULL,
    "sku_id" bigint NOT NULL,
    "quantity" bigint NOT NULL,
    "delivery_date" varchar NOT NULL,
    "delivery_place" varchar NOT NULL,
    "supplier_list" varchar,
    "notes" varchar,
    "status" int NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '材料询价明细';

-- 将该建表 SQL 语句，添加到 bpcm-module-material-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "material_rfq_quote" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rfq_item_id" bigint NOT NULL,
    "price" bigint NOT NULL,
    "amount" bigint NOT NULL,
    "tax" bigint NOT NULL,
    "tax_amount" bigint NOT NULL,
    "supplier_id" varchar NOT NULL,
    "notes" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '采购报价明细';

-- 将该建表 SQL 语句，添加到 bpcm-module-material-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "material_budget" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar NOT NULL,
    "category_id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "sub_type" int NOT NULL,
    "task_status" int NOT NULL,
    "notes" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '材料预算';